-- +migrate Up
CREATE TABLE event_invited_members (
    EVENTID INTEGER,
    USERID INTEGER,
    ANSWERTYPE INTEGER(1),
    PRIMARY KEY(EVENTID, USERID),
    FOREIGN KEY(EVENTID) REFERENCES events(ID),
    FOREIGN KEY(USERID) REFERENCES users(ID)
);