-- +migrate Up
CREATE TABLE events (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUPID INTEGER NOT NULL,
    AUTHORID INTEGER NOT NULL,
    EVENTTITLE TEXT NOT NULL,
    EVENTDESCRIPTION TEXT NOT NULL,
    STARTDATE TEXT NOT NULL,
    ENDDATE TEXT NOT NULL,
    CREATEDAT TEXT NOT NULL,
    FOREIGN KEY(GROUPID) REFERENCES groups(ID),
    FOREIGN KEY(AUTHORID) REFERENCES users(ID)
);