-- +migrate Up
CREATE TABLE group_invites (
    GROUPID INTEGER,
    INVITEDID INTEGER,
    INVITERID INTEGER,
    PRIMARY KEY (GROUPID, INVITEDID, INVITERID),
    FOREIGN KEY(GROUPID) REFERENCES groups(ID),
    FOREIGN KEY(INVITEDID) REFERENCES users(ID),
    FOREIGN KEY(INVITERID) REFERENCES users(ID)
);