-- +migrate Up
CREATE TABLE group_requests (
    GROUPID INTEGER,
    REQUESTERID INTEGER,
    PRIMARY KEY (GROUPID, REQUESTERID),
    FOREIGN KEY(GROUPID) REFERENCES groups(ID),
    FOREIGN KEY(REQUESTERID) REFERENCES users(ID)
);