-- +migrate Up
CREATE TABLE comments (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
    POSTID INTEGER NOT NULL,
    USERID INTEGER NOT NULL,
    CONTENT text NOT NULL,
    CREATEDAT text NOT NULL,
    FOREIGN KEY(POSTID) REFERENCES posts(ID),
    FOREIGN KEY(USERID) REFERENCES users(ID)
);