-- +migrate Up
CREATE TABLE notifications (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERID INTEGER NOT NULL,
    CONTENT TEXT NOT NULL,
    NOTIFICATIONTYPE INTEGER(1) NOT NULL,
    ISREAD BOOLEAN NOT NULL,
    CREATEDAT TEXT NOT NULL,
    FOLLOWERID INTEGER,
    GROUPID INTEGER,
    EVENTID INTEGER,
    FOREIGN KEY(USERID) REFERENCES users(ID),
    FOREIGN KEY(FOLLOWERID) REFERENCES users(ID),
    FOREIGN KEY(GROUPID) REFERENCES groups(ID),
    FOREIGN KEY(EVENTID) REFERENCES events(ID)
);