-- +migrate Up
CREATE TABLE conversations (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER1ID INTEGER,
    USER2ID INTEGER,
    createdAt TEXT NOT NULL,
    GROUPID INTEGER,
    FOREIGN KEY(USER1ID) REFERENCES users(ID),
    FOREIGN KEY(USER2ID) REFERENCES users(ID),
    FOREIGN KEY(GROUPID) REFERENCES groups(ID)
);
