-- +migrate Up
CREATE TABLE group_members (
    GROUPID INTEGER NOT NULL,
    MEMBERID INtEGER NOT NULL,
    PRIMARY KEY (GROUPID, MEMBERID),
    FOREIGN KEY(GROUPID) REFERENCES groups(ID),
    FOREIGN KEY(MEMBERID) REFERENCES users(ID)
);