-- +migrate Up
CREATE TABLE follower_connections (
    FOLLOWEDID INTEGER,
    FOLLOWERID INTEGER,
    PRIMARY KEY (FOLLOWEDID, FOLLOWERID),
    FOREIGN KEY(FOLLOWEDID) REFERENCES users(ID),
    FOREIGN KEY(FOLLOWERID) REFERENCES users(ID)
);